### ISSUE TITLE
Similar dataset

### ISSUE THREAD

**Issue by hsiaoyi0504** [YCKung/character-level-classification-using-neural-networks#1]
Just want to share with other people that have interest in this project.
There is a dataset available on Kaggle: https://www.kaggle.com/alaeddineayadi/obfuscated-multiclassification.

**Comment by AngusKung** [comment]
Wow! It's indeed extremely similar, it also have 12 classes!
Thanks for sharing :)

**Comment by hsiaoyi0504** [comment]
@YCKung Do you think it's possible to add this to `README.pdf` ? Just want to share with other people who are interested in this task. Or I can make a pull request in `README.md` because I can't edit the `README.pdf`.
